### ISSUE TITLE
无法运行run.ps1，因为在此系统上禁止运行脚本

### ISSUE THREAD

**Issue by nefusmzj** [yongxin-ms/DisableSogouNetwork#2]
Windows11系统，以管理员身份启动powershell后，运行run.ps1会有错误提示，

>无法运行run.ps1，因为在此系统上禁止运行脚本

解决办法是，放开powershell的安全权限限制，即输入```set-ExecutionPolicy RemoteSigned```，然后再运行run.ps1即可。

恢复powershell的安全限制的方法是```set-ExecutionPolicy Default```

**Comment by Noa886** [comment]
.\run.ps1 : 无法加载文件 C:\Users\Administrator\Desktop\run.ps1。未对文件 C:\Users\Administrator\Desktop\run.ps1 进
行数字签名。无法在当前系统上运行该脚本。有关运行脚本和设置执行策略的详细信息，请参阅 https:/go.microsoft.com/fwlink/?Li
nkID=135170 中的 about_Execution_Policies。
所在位置 行:1 字符: 1
+ .\run.ps1
+ ~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) []，PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by Noa886** [comment]
> .\run.ps1 : 无法加载文件 C:\Users\Administrator\Desktop\run.ps1。未对文件 C:\Users\Administrator\Desktop\run.ps1 进 行数字签名。无法在当前系统上运行该脚本。有关运行脚本和设置执行策略的详细信息，请参阅 https:/go.microsoft.com/fwlink/?Li nkID=135170 中的 about_Execution_Policies。 所在位置 行:1 字符: 1
> 
> * .\run.ps1
> * ```
>     + CategoryInfo          : SecurityError: (:) []，PSSecurityException
>     + FullyQualifiedErrorId : UnauthorizedAccess
>   ```

- [ ] set-ExecutionPolicy  Bypass 

      解决问题
